server.port=8080

spring.datasource.url=jdbc:postgresql://8.133.176.179:5432/diet_tracker?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=postgres
spring.datasource.password=na6021023
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

spring.sql.init.mode=never

logging.level.org.springframework.web=DEBUG
logging.level.com.diettracker=DEBUG
