import { useState } from 'react'
import { api } from '../api/client.js'
import { Icon } from '../components/Icons.jsx'
import { StateView } from '../components/StateView.jsx'

export function CustomFoodsPage() {
  const [form, setForm] = useState({ userRef: '', foodId: '' }); const [state, setState] = useState('idle'); const [items, setItems] = useState([]); const [error, setError] = useState(null)
  async function search(event) { event.preventDefault(); setState('loading'); setError(null); try { const result = await api(`/custom-foods?userRef=${encodeURIComponent(form.userRef)}&foodId=${encodeURIComponent(form.foodId)}`); setItems(result); setState(result.length?'success':'empty') } catch (failure) { setError(failure); setState(failure.status===403?'forbidden':failure.status===404?'empty':'error') } }
  return <><header className="page-head"><div><span>只读诊断</span><h1>用户私有食品</h1><p>使用稳定的脱敏用户编号与食品 ID 精确定位，不显示 openid 或个人资料。</p></div></header><section className="diagnostic-search"><div><Icon name="shield"/><p><strong>严格只读</strong><span>不能转为公共食品，也不能代用户编辑。</span></p></div><form onSubmit={search}><label><span>脱敏用户编号</span><input required pattern="usr_[a-f0-9]{32}" placeholder="usr_…" value={form.userRef} onChange={(e)=>setForm((v)=>({...v,userRef:e.target.value}))}/></label><label><span>食品 ID</span><input required type="number" min="1" placeholder="例如 128" value={form.foodId} onChange={(e)=>setForm((v)=>({...v,foodId:e.target.value}))}/></label><button className="button primary" disabled={state==='loading'}><Icon name="search"/>{state==='loading'?'查询中…':'精确查询'}</button></form></section>{state === 'success' ? <section className="diagnostic-result"><header><div><span>匹配结果</span><strong>{items[0].name}</strong></div><code>{items[0].userRef}</code></header><dl><div><dt>营养基准</dt><dd>{items[0].baseAmount}{items[0].baseUnit}</dd></div><div><dt>热量</dt><dd>{items[0].calories} kcal</dd></div><div><dt>蛋白质</dt><dd>{items[0].protein} g</dd></div><div><dt>脂肪</dt><dd>{items[0].fat} g</dd></div><div><dt>碳水</dt><dd>{items[0].carbs} g</dd></div></dl></section> : state !== 'idle' && state !== 'loading' ? <StateView state={state} title={state==='empty'?'未找到匹配食品':state==='forbidden'?'无诊断权限':'查询失败'} detail={state==='empty'?'请同时核对脱敏用户编号和食品 ID。':error?.message} requestId={error?.requestId} onRetry={state==='error'?()=>setState('idle'):undefined}/> : null}</>
}
